// Generated by gencpp from file mora_husky_robot_localization/SetDatum.msg
// DO NOT EDIT!


#ifndef MORA_HUSKY_ROBOT_LOCALIZATION_MESSAGE_SETDATUM_H
#define MORA_HUSKY_ROBOT_LOCALIZATION_MESSAGE_SETDATUM_H

#include <ros/service_traits.h>


#include <mora_husky_robot_localization/SetDatumRequest.h>
#include <mora_husky_robot_localization/SetDatumResponse.h>


namespace mora_husky_robot_localization
{

struct SetDatum
{

typedef SetDatumRequest Request;
typedef SetDatumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDatum
} // namespace mora_husky_robot_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mora_husky_robot_localization::SetDatum > {
  static const char* value()
  {
    return "fe903ca95d0210defda73a1629604439";
  }

  static const char* value(const ::mora_husky_robot_localization::SetDatum&) { return value(); }
};

template<>
struct DataType< ::mora_husky_robot_localization::SetDatum > {
  static const char* value()
  {
    return "mora_husky_robot_localization/SetDatum";
  }

  static const char* value(const ::mora_husky_robot_localization::SetDatum&) { return value(); }
};


// service_traits::MD5Sum< ::mora_husky_robot_localization::SetDatumRequest> should match 
// service_traits::MD5Sum< ::mora_husky_robot_localization::SetDatum > 
template<>
struct MD5Sum< ::mora_husky_robot_localization::SetDatumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mora_husky_robot_localization::SetDatum >::value();
  }
  static const char* value(const ::mora_husky_robot_localization::SetDatumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mora_husky_robot_localization::SetDatumRequest> should match 
// service_traits::DataType< ::mora_husky_robot_localization::SetDatum > 
template<>
struct DataType< ::mora_husky_robot_localization::SetDatumRequest>
{
  static const char* value()
  {
    return DataType< ::mora_husky_robot_localization::SetDatum >::value();
  }
  static const char* value(const ::mora_husky_robot_localization::SetDatumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mora_husky_robot_localization::SetDatumResponse> should match 
// service_traits::MD5Sum< ::mora_husky_robot_localization::SetDatum > 
template<>
struct MD5Sum< ::mora_husky_robot_localization::SetDatumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mora_husky_robot_localization::SetDatum >::value();
  }
  static const char* value(const ::mora_husky_robot_localization::SetDatumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mora_husky_robot_localization::SetDatumResponse> should match 
// service_traits::DataType< ::mora_husky_robot_localization::SetDatum > 
template<>
struct DataType< ::mora_husky_robot_localization::SetDatumResponse>
{
  static const char* value()
  {
    return DataType< ::mora_husky_robot_localization::SetDatum >::value();
  }
  static const char* value(const ::mora_husky_robot_localization::SetDatumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORA_HUSKY_ROBOT_LOCALIZATION_MESSAGE_SETDATUM_H
